### ISSUE TITLE
python2.7 generators

### ISSUE THREAD

**Issue by dilyanpalauzov** [whot/libevdev-python#5]
Python 2.7 does not seem to like function containing `yield`, which are hence generators, and `return` with parameters.  `devices.py:events()` has` return []` and later `yield`, so the first shall be replaced with `yield\nreturn`.

Likewise for `devices.py:sync()`.

**Comment by whot** [comment]
sorry, this wrapper is python 3 only

**Comment by dilyanpalauzov** [comment]
Why isn't this mentioned at Categories under https://pypi.python.org/pypi/libevdev, as it is done for https://pypi.python.org/pypi/Django/2.0.2 ?

**Comment by whot** [comment]
oops, that commit was after the 0.2 version and I never pushed it to pypi. Pushed now as 0.3, thanks
